-- Калькулятор ЮР (dashbord/calcUr/mainur.js): цены и названия позиций переносятся в БД.
-- pricecalc_ur — цены (итоговые рубли, прежний коэффициент 165% уже применён), редактируются в dashbord/priceChange.php?calc=ur.
-- titel_calc_ur — названия позиций (name = id узла дерева, в некоторых id есть кириллическая буква «с»), редактируются в dashbord/titelPriceChange.php?calc=ur.
-- Стартовые значения совпадают с прежними захардкоженными в mainur.js, поэтому калькулятор считает так же, как до переноса.
-- Скрипт идемпотентный: таблицы создаются, только если их нет, строки добавляются, только если такого name ещё нет.

CREATE TABLE IF NOT EXISTS `pricecalc_ur` LIKE `pricecalc`;

CREATE TABLE IF NOT EXISTS `titel_calc_ur` LIKE `titel_calc`;

-- 1. Цены (214 позиций)
INSERT INTO `pricecalc_ur` (`name`, `price`)
SELECT * FROM (
    SELECT 'petchat_A4_mt120' AS `name`, '13.07' AS `price`
    UNION ALL SELECT 'petchat_A4_mt160', '13.07'
    UNION ALL SELECT 'petchat_A4_mt200', '17.42'
    UNION ALL SELECT 'petchat_A4_mt250', '21.78'
    UNION ALL SELECT 'petchat_A4_mt300', '30.49'
    UNION ALL SELECT 'petchat_A4_gl170', '21.78'
    UNION ALL SELECT 'petchat_A4_gl250', '26.14'
    UNION ALL SELECT 'petchat_A4_klk250', '78.41'
    UNION ALL SELECT 'petchat_A4_sk', '52.27'
    UNION ALL SELECT 'petchat_A3_mt160', '26.14'
    UNION ALL SELECT 'petchat_A3_mt200', '34.85'
    UNION ALL SELECT 'petchat_A3_mt250', '43.56'
    UNION ALL SELECT 'petchat_A3_mt280', '52.27'
    UNION ALL SELECT 'petchat_A3_gl170', '43.56'
    UNION ALL SELECT 'petchat_A3_gl250', '102.37'
    UNION ALL SELECT 'petchat_A3_klk250', '152.46'
    UNION ALL SELECT 'petchat_copy_glass', '9.9'
    UNION ALL SELECT 'petchat_chet_A4_odn', '15.84'
    UNION ALL SELECT 'petchat_chet_A4_dvx', '31.68'
    UNION ALL SELECT 'petchat_chet_A3_odn', '31.68'
    UNION ALL SELECT 'petchat_chet_A3_dvx', '63.36'
    UNION ALL SELECT 'petchat_chet_A2_z0', '69.3'
    UNION ALL SELECT 'petchat_chet_A2_z20', '138.6'
    UNION ALL SELECT 'petchat_chet_A1_z0', '99'
    UNION ALL SELECT 'petchat_chet_A1_z20', '198'
    UNION ALL SELECT 'petchat_chet_A0_z0', '237.6'
    UNION ALL SELECT 'petchat_chet_A0_z20', '475.2'
    UNION ALL SELECT 'petchat_chet_ns_z0', '232.1'
    UNION ALL SELECT 'petchat_chet_ns_z20', '475.2'
    UNION ALL SELECT 'petchat_chet_A2_mat', '594'
    UNION ALL SELECT 'petchat_chet_A2_gl', '811.8'
    UNION ALL SELECT 'petchat_chet_A2_kalka', '415.8'
    UNION ALL SELECT 'petchat_chet_A2_samokl', '1089'
    UNION ALL SELECT 'petchat_chet_A2_xolst', '1584'
    UNION ALL SELECT 'petchat_chet_A1_mat', '811.8'
    UNION ALL SELECT 'petchat_chet_A1_gl', '1386'
    UNION ALL SELECT 'petchat_chet_A1_kalka', '594'
    UNION ALL SELECT 'petchat_chet_A1_samokl', '1287'
    UNION ALL SELECT 'petchat_chet_A1_xolst', '2376'
    UNION ALL SELECT 'petchat_chet_A0_mat', '1623.6'
    UNION ALL SELECT 'petchat_chet_A0_gl', '2574'
    UNION ALL SELECT 'petchat_chet_A0_kalka', '1188'
    UNION ALL SELECT 'petchat_chet_A0_samokl', '2376'
    UNION ALL SELECT 'petchat_chet_A0_xolst', '4752'
    UNION ALL SELECT 'petchat_chet_ns_mat', '1623.6'
    UNION ALL SELECT 'petchat_chet_ns_gl', '2574'
    UNION ALL SELECT 'petchat_chet_ns_kalka', '1188'
    UNION ALL SELECT 'petchat_chet_ns_samokl', '2376'
    UNION ALL SELECT 'petchat_chet_ns_xolst', '4752'
    UNION ALL SELECT 'petchat_bw_A4_odn', '3.76'
    UNION ALL SELECT 'petchat_bw_A4_dvx', '5.94'
    UNION ALL SELECT 'petchat_bw_A3_odn', '7.92'
    UNION ALL SELECT 'petchat_bw_A3_dvx', '11.88'
    UNION ALL SELECT 'petchat_bw_A2_80', '39.6'
    UNION ALL SELECT 'petchat_bw_A2_90', '79.2'
    UNION ALL SELECT 'petchat_bw_A1_80', '59.4'
    UNION ALL SELECT 'petchat_bw_A1_90', '118.8'
    UNION ALL SELECT 'petchat_bw_A0_80', '118.8'
    UNION ALL SELECT 'petchat_bw_A0_90', '237.6'
    UNION ALL SELECT 'petchat_bw_ns_80', '118.8'
    UNION ALL SELECT 'petchat_bw_ns_90', '237.6'
    UNION ALL SELECT 'pereplet_pl_A4_m', '118.8'
    UNION ALL SELECT 'pereplet_pl_A4_s', '158.4'
    UNION ALL SELECT 'pereplet_pl_A4_b', '198'
    UNION ALL SELECT 'pereplet_pl_A3_m', '237.6'
    UNION ALL SELECT 'pereplet_pl_A3_s', '316.8'
    UNION ALL SELECT 'pereplet_pl_A3_b', '396'
    UNION ALL SELECT 'pereplet_tv_5', '784.08'
    UNION ALL SELECT 'pereplet_tv_10', '871.2'
    UNION ALL SELECT 'pereplet_tv_16', '958.32'
    UNION ALL SELECT 'pereplet_tv_24', '1034.55'
    UNION ALL SELECT 'pereplet_vs_k', '65.34'
    UNION ALL SELECT 'pereplet_vs_f', '108.9'
    UNION ALL SELECT 'pereplet_pl_per', '108.9'
    UNION ALL SELECT 'pereplet_mt', '250'
    UNION ALL SELECT 'prochee_r', '16.5'
    UNION ALL SELECT 'prochee_rr', '11.55'
    UNION ALL SELECT 'prochee_opf', '65.34'
    UNION ALL SELECT 'prochee_rk', '21.78'
    UNION ALL SELECT 'prochee_nt', '412.5'
    UNION ALL SELECT 'prochee_df', '43.56'
    UNION ALL SELECT 'prochee_shiv', '174.24'
    UNION ALL SELECT 'prochee_perfor', '1.09'
    UNION ALL SELECT 'prochee_stepler', '13.07'
    UNION ALL SELECT 'prochee_bigovka', '13.07'
    UNION ALL SELECT 'prochee_tisn', '261.36'
    UNION ALL SELECT 'prochee_dost', '1306.8'
    UNION ALL SELECT 'prochee_ps', '87.12'
    UNION ALL SELECT 'prochee_A4', '10.89'
    UNION ALL SELECT 'prochee_A3', '21.78'
    UNION ALL SELECT 'prochee_lam_0_A6_g', '108.9'
    UNION ALL SELECT 'prochee_lam_10_A6_g', '87.12'
    UNION ALL SELECT 'prochee_lam_50_A6_g', '65.34'
    UNION ALL SELECT 'prochee_lam_0_A5_g', '119.79'
    UNION ALL SELECT 'prochee_lam_10_A5_g', '98.01'
    UNION ALL SELECT 'prochee_lam_50_A5_g', '76.23'
    UNION ALL SELECT 'prochee_lam_0_A4_g', '141.57'
    UNION ALL SELECT 'prochee_lam_10_A4_g', '119.79'
    UNION ALL SELECT 'prochee_lam_50_A4_g', '98.01'
    UNION ALL SELECT 'prochee_lam_0_A3_g', '185.13'
    UNION ALL SELECT 'prochee_lam_10_A3_g', '163.35'
    UNION ALL SELECT 'prochee_lam_50_A3_g', '141.57'
    UNION ALL SELECT 'prochee_lam_0_A6_m', '119.79'
    UNION ALL SELECT 'prochee_lam_10_A6_m', '98.01'
    UNION ALL SELECT 'prochee_lam_50_A6_m', '76.23'
    UNION ALL SELECT 'prochee_lam_0_A5_m', '130.68'
    UNION ALL SELECT 'prochee_lam_10_A5_m', '108.9'
    UNION ALL SELECT 'prochee_lam_50_A5_m', '87.12'
    UNION ALL SELECT 'prochee_lam_0_A4_m', '152.46'
    UNION ALL SELECT 'prochee_lam_10_A4_m', '130.68'
    UNION ALL SELECT 'prochee_lam_50_A4_m', '108.9'
    UNION ALL SELECT 'prochee_lam_0_A3_m', '196.02'
    UNION ALL SELECT 'prochee_lam_10_A3_m', '174.24'
    UNION ALL SELECT 'prochee_lam_50_A3_m', '152.46'
    UNION ALL SELECT 'prochee_falc_0', '43.56'
    UNION ALL SELECT 'prochee_falc_100', '32.67'
    UNION ALL SELECT 'prochee_ocr_0', '43.56'
    UNION ALL SELECT 'prochee_ocr_50', '32.67'
    UNION ALL SELECT 'prochee_ocr_100', '17.42'
    UNION ALL SELECT 'prochee_dc', '200'
    UNION ALL SELECT 'prochee_dk', '200'
    UNION ALL SELECT 'dis_one_ysl', '32'
    UNION ALL SELECT 'dis_one_vv', '550'
    UNION ALL SELECT 'dis_fd', '350'
    UNION ALL SELECT 'dis_one_fr', '2200'
    UNION ALL SELECT 'dis_one_vm', '2200'
    UNION ALL SELECT 'dis_one_rl', '7700'
    UNION ALL SELECT 'dis_viz_1s_bw', '440'
    UNION ALL SELECT 'dis_viz_2s_bw', '500'
    UNION ALL SELECT 'dis_viz_1s_c', '550'
    UNION ALL SELECT 'dis_viz_2s_c', '650'
    UNION ALL SELECT 'dis_db_db', '65'
    UNION ALL SELECT 'dis_db_tc', '75'
    UNION ALL SELECT 'dis_pet_kp', '770'
    UNION ALL SELECT 'dis_pet_hm', '550'
    UNION ALL SELECT 'dis_pet_ott', '770'
    UNION ALL SELECT 'dis_pet_iks', '1100'
    UNION ALL SELECT 'dis_osn_gbr', '550'
    UNION ALL SELECT 'dis_osn_pr', '110'
    UNION ALL SELECT 'dis_osn_karm', '550'
    UNION ALL SELECT 'dis_osn_avto_m', '550'
    UNION ALL SELECT 'dis_osn_avto_b', '825'
    UNION ALL SELECT 'dis_krask_1', '400'
    UNION ALL SELECT 'dis_krask_2', '550'
    UNION ALL SELECT 'dis_krask_3', '300'
    UNION ALL SELECT 'dis_krask_4', '400'
    UNION ALL SELECT 'dis_krask_5', '150'
    UNION ALL SELECT 'baget_nak_5_A4', '85'
    UNION ALL SELECT 'baget_nak_5_A3', '170'
    UNION ALL SELECT 'baget_nak_5_A2', '340'
    UNION ALL SELECT 'baget_nak_5_A1', '680'
    UNION ALL SELECT 'baget_nak_5_A0', '1360'
    UNION ALL SELECT 'baget_nak_5_m2', '1360'
    UNION ALL SELECT 'baget_nak_10_A4', '110'
    UNION ALL SELECT 'baget_nak_10_A3', '220'
    UNION ALL SELECT 'baget_nak_10_A2', '440'
    UNION ALL SELECT 'baget_nak_10_A1', '880'
    UNION ALL SELECT 'baget_nak_10_A0', '1760'
    UNION ALL SELECT 'baget_nak_10_m2', '1760'
    UNION ALL SELECT 'baget_nak_st_5_A4', '75'
    UNION ALL SELECT 'baget_nak_st_5_A3', '150'
    UNION ALL SELECT 'baget_nak_st_5_A2', '300'
    UNION ALL SELECT 'baget_nak_st_5_A1', '600'
    UNION ALL SELECT 'baget_nak_st_5_A0', '1200'
    UNION ALL SELECT 'baget_nak_st_5_m2', '1200'
    UNION ALL SELECT 'baget_nak_st_10_A4', '100'
    UNION ALL SELECT 'baget_nak_st_10_A3', '200'
    UNION ALL SELECT 'baget_nak_st_10_A2', '400'
    UNION ALL SELECT 'baget_nak_st_10_A1', '800'
    UNION ALL SELECT 'baget_nak_st_10_A0', '1600'
    UNION ALL SELECT 'baget_nak_st_10_m2', '1600'
    UNION ALL SELECT 'falc_A4', '8'
    UNION ALL SELECT 'falc_A3', '4.76'
    UNION ALL SELECT 'falc_A2', '9.51'
    UNION ALL SELECT 'falc_A1', '15.86'
    UNION ALL SELECT 'falc_A0', '17.44'
    UNION ALL SELECT 'scan_color_A2', '38.05'
    UNION ALL SELECT 'scan_color_A1', '57.08'
    UNION ALL SELECT 'scan_color_A0', '114.16'
    UNION ALL SELECT 'prochee_scan_0_A4_av', '21.78'
    UNION ALL SELECT 'prochee_scan_10_A4_av', '17.42'
    UNION ALL SELECT 'prochee_scan_50_A4_av', '13.07'
    UNION ALL SELECT 'prochee_scan_100_A4_av', '8.71'
    UNION ALL SELECT 'prochee_scan_500_A4_av', '6.53'
    UNION ALL SELECT 'prochee_scan_0_A4_r', '32.67'
    UNION ALL SELECT 'prochee_scan_10_A4_r', '26.14'
    UNION ALL SELECT 'prochee_scan_50_A4_r', '19.6'
    UNION ALL SELECT 'prochee_scan_100_A4_r', '13.07'
    UNION ALL SELECT 'prochee_scan_500_A4_r', '9.8'
    UNION ALL SELECT 'prochee_scan_0_A3_av', '32.67'
    UNION ALL SELECT 'prochee_scan_10_A3_av', '26.14'
    UNION ALL SELECT 'prochee_scan_50_A3_av', '19.6'
    UNION ALL SELECT 'prochee_scan_100_A3_av', '15.25'
    UNION ALL SELECT 'prochee_scan_500_A3_av', '10.89'
    UNION ALL SELECT 'prochee_scan_0_A3_r', '49.01'
    UNION ALL SELECT 'prochee_scan_10_A3_r', '39.2'
    UNION ALL SELECT 'prochee_scan_50_A3_r', '29.4'
    UNION ALL SELECT 'prochee_scan_100_A3_r', '22.87'
    UNION ALL SELECT 'prochee_scan_500_A3_r', '16.34'
    UNION ALL SELECT 'prochee_scan_0_A2', '76.23'
    UNION ALL SELECT 'prochee_scan_10_A2', '54.45'
    UNION ALL SELECT 'prochee_scan_50_A2', '43.56'
    UNION ALL SELECT 'prochee_scan_100_A2', '32.67'
    UNION ALL SELECT 'prochee_scan_500_A2', '26.14'
    UNION ALL SELECT 'prochee_scan_0_A1', '141.57'
    UNION ALL SELECT 'prochee_scan_10_A1', '119.79'
    UNION ALL SELECT 'prochee_scan_50_A1', '98.01'
    UNION ALL SELECT 'prochee_scan_100_A1', '76.23'
    UNION ALL SELECT 'prochee_scan_500_A1', '54.45'
    UNION ALL SELECT 'prochee_scan_0_A0', '239.58'
    UNION ALL SELECT 'prochee_scan_10_A0', '206.91'
    UNION ALL SELECT 'prochee_scan_50_A0', '185.13'
    UNION ALL SELECT 'prochee_scan_100_A0', '163.35'
    UNION ALL SELECT 'prochee_scan_500_A0', '141.57'
) AS new_rows
WHERE NOT EXISTS (SELECT 1 FROM `pricecalc_ur` p WHERE p.`name` = new_rows.`name`);

-- 2. Названия позиций (306 узлов)
INSERT INTO `titel_calc_ur` (`name`, `titel`)
SELECT * FROM (
    SELECT 'aa' AS `name`, 'Цветная печать' AS `titel`
    UNION ALL SELECT 'aaa', 'формат А4'
    UNION ALL SELECT 'aaaa', 'обычная бумага 80 гр.'
    UNION ALL SELECT 'aaaab', 'двусторонняя печать'
    UNION ALL SELECT 'aaaac', 'одностороннее копирование со стекла'
    UNION ALL SELECT 'aaaad', 'двустороннее копирование со стекла'
    UNION ALL SELECT 'aaab', 'матовая бумага 120 гр.'
    UNION ALL SELECT 'aaabb', 'двусторонняя печать'
    UNION ALL SELECT 'aaabс', 'одностороннее копирование со стекла'
    UNION ALL SELECT 'aaabd', 'двустороннее копирование со стекла'
    UNION ALL SELECT 'aaac', 'матовая бумага 160 гр.'
    UNION ALL SELECT 'aaacb', 'двусторонняя печать'
    UNION ALL SELECT 'aaacс', 'одностороннее копирование со стекла'
    UNION ALL SELECT 'aaacd', 'двустороннее копирование со стекла'
    UNION ALL SELECT 'aaad', 'матовая бумага 200 гр.'
    UNION ALL SELECT 'aaadb', 'двусторонняя печать'
    UNION ALL SELECT 'aaadc', 'одностороннее копирование со стекла'
    UNION ALL SELECT 'aaadd', 'двустороннее копирование со стекла'
    UNION ALL SELECT 'aaae', 'матовая бумага 250 гр.'
    UNION ALL SELECT 'aaaeb', 'двусторонняя печать'
    UNION ALL SELECT 'aaaec', 'одностороннее копирование со стекла'
    UNION ALL SELECT 'aaaed', 'двустороннее копирование со стекла'
    UNION ALL SELECT 'aaaf', 'матовая бумага 300 гр.'
    UNION ALL SELECT 'aaafb', 'двусторонняя печать'
    UNION ALL SELECT 'aaafc', 'одностороннее копирование со стекла'
    UNION ALL SELECT 'aaafd', 'двустороннее копирование со стекла'
    UNION ALL SELECT 'aaag', 'глянцевая бумага 170 гр.'
    UNION ALL SELECT 'aaagb', 'двусторонняя печать'
    UNION ALL SELECT 'aaagc', 'одностороннее копирование со стекла'
    UNION ALL SELECT 'aaagd', 'двустороннее копирование со стекла'
    UNION ALL SELECT 'aaah', 'глянцевая бумага 250 гр.'
    UNION ALL SELECT 'aaahb', 'двусторонняя печать'
    UNION ALL SELECT 'aaahc', 'одностороннее копирование со стекла'
    UNION ALL SELECT 'aaahd', 'двустороннее копирование со стекла'
    UNION ALL SELECT 'aaaj', 'калька 250 гр.'
    UNION ALL SELECT 'aaajb', 'двусторонняя печать'
    UNION ALL SELECT 'aaajc', 'одностороннее копирование со стекла'
    UNION ALL SELECT 'aaajd', 'двустороннее копирование со стекла'
    UNION ALL SELECT 'aaai', 'самоклейка'
    UNION ALL SELECT 'aab', 'формат А3'
    UNION ALL SELECT 'aaba', 'обычная бумага 80 гр.'
    UNION ALL SELECT 'aabab', 'двусторонняя печать'
    UNION ALL SELECT 'aabac', 'одностороннее копирование со стекла'
    UNION ALL SELECT 'aabad', 'двустороннее копирование со стекла'
    UNION ALL SELECT 'aabb', 'матовая бумага 160 гр.'
    UNION ALL SELECT 'aabbb', 'двусторонняя печать'
    UNION ALL SELECT 'aabbc', 'одностороннее копирование со стекла'
    UNION ALL SELECT 'aabbd', 'двустороннее копирование со стекла'
    UNION ALL SELECT 'aabc', 'матовая бумага 200 гр.'
    UNION ALL SELECT 'aabcb', 'двусторонняя печать'
    UNION ALL SELECT 'aabcc', 'одностороннее копирование со стекла'
    UNION ALL SELECT 'aabcd', 'двустороннее копирование со стекла'
    UNION ALL SELECT 'aabd', 'матовая бумага 250 гр.'
    UNION ALL SELECT 'aabdb', 'двусторонняя печать'
    UNION ALL SELECT 'aabdc', 'одностороннее копирование со стекла'
    UNION ALL SELECT 'aabdd', 'двустороннее копирование со стекла'
    UNION ALL SELECT 'aabe', 'матовая бумага 280 гр.'
    UNION ALL SELECT 'aabeb', 'двусторонняя печать'
    UNION ALL SELECT 'aabec', 'одностороннее копирование со стекла'
    UNION ALL SELECT 'aabed', 'двустороннее копирование со стекла'
    UNION ALL SELECT 'aabf', 'глянцевая бумага 170 гр.'
    UNION ALL SELECT 'aabfb', 'двусторонняя печать'
    UNION ALL SELECT 'aabfс', 'одностороннее копирование со стекла'
    UNION ALL SELECT 'aabfd', 'двустороннее копирование со стекла'
    UNION ALL SELECT 'aabg', 'глянцевая бумага 250г гр.'
    UNION ALL SELECT 'aabgb', 'двусторонняя печать'
    UNION ALL SELECT 'aabgс', 'одностороннее копирование со стекла'
    UNION ALL SELECT 'aabgd', 'двустороннее копирование со стекла'
    UNION ALL SELECT 'aabh', 'калька бумага 250 гр.'
    UNION ALL SELECT 'aabhb', 'двусторонняя печать'
    UNION ALL SELECT 'aabhс', 'одностороннее копирование со стекла'
    UNION ALL SELECT 'aabhd', 'двустороннее копирование со стекла'
    UNION ALL SELECT 'aac', 'формат А2'
    UNION ALL SELECT 'aaca', 'обычная бумага 80 гр.'
    UNION ALL SELECT 'aacab', 'заливка более 20%'
    UNION ALL SELECT 'aacb', 'матовая бумага 180 гр.'
    UNION ALL SELECT 'aacc', 'глянцевая бумага HP'
    UNION ALL SELECT 'aacd', 'калька 90 гр.'
    UNION ALL SELECT 'aace', 'самоклейка'
    UNION ALL SELECT 'aacf', 'холст 320 гр.'
    UNION ALL SELECT 'aad', 'формат А1'
    UNION ALL SELECT 'aada', 'обычная бумага 80 гр.'
    UNION ALL SELECT 'aadab', 'заливка более 20%'
    UNION ALL SELECT 'aadb', 'матовая бумага 180 гр.'
    UNION ALL SELECT 'aadc', 'глянцевая бумага HP'
    UNION ALL SELECT 'aadd', 'калька 90 гр.'
    UNION ALL SELECT 'aade', 'самоклейка'
    UNION ALL SELECT 'aadf', 'холст 320 гр.'
    UNION ALL SELECT 'aae', 'формат А0'
    UNION ALL SELECT 'aaea', 'обычная бумага 80 гр.'
    UNION ALL SELECT 'aaeab', 'заливка более 20%'
    UNION ALL SELECT 'aaeb', 'матовая бумага 180 гр.'
    UNION ALL SELECT 'aaec', 'глянцевая бумага HP'
    UNION ALL SELECT 'aaed', 'калька 90 гр.'
    UNION ALL SELECT 'aaee', 'самоклейка'
    UNION ALL SELECT 'aaef', 'холст 320 гр.'
    UNION ALL SELECT 'aaf', 'нестандартный формат'
    UNION ALL SELECT 'aafa', 'обычная бумага 80 гр.'
    UNION ALL SELECT 'aafab', 'заливка более 20%'
    UNION ALL SELECT 'aafb', 'матовая бумага 180 гр.'
    UNION ALL SELECT 'aafc', 'глянцевая бумага HP'
    UNION ALL SELECT 'aafd', 'калька 90 гр.'
    UNION ALL SELECT 'aafe', 'самоклейка'
    UNION ALL SELECT 'aaff', 'холст 320 гр.'
    UNION ALL SELECT 'ab', 'Черно белая печать'
    UNION ALL SELECT 'aba', 'формат А4'
    UNION ALL SELECT 'abaa', 'обычная бумага 80 гр.'
    UNION ALL SELECT 'abaab', 'двусторонняя печать'
    UNION ALL SELECT 'abaaс', 'одностороннее копирование со стекла'
    UNION ALL SELECT 'abaad', 'двустороннее копирование со стекла'
    UNION ALL SELECT 'abab', 'матовая бумага 120 гр.'
    UNION ALL SELECT 'ababb', 'двусторонняя печать'
    UNION ALL SELECT 'ababс', 'одностороннее копирование со стекла'
    UNION ALL SELECT 'ababd', 'двустороннее копирование со стекла'
    UNION ALL SELECT 'abac', 'матовая бумага 160 гр.'
    UNION ALL SELECT 'abacb', 'двусторонняя печать'
    UNION ALL SELECT 'abacс', 'одностороннее копирование со стекла'
    UNION ALL SELECT 'abacd', 'двустороннее копирование со стекла'
    UNION ALL SELECT 'abad', 'матовая бумага 200 гр.'
    UNION ALL SELECT 'abadb', 'двусторонняя печать'
    UNION ALL SELECT 'abadс', 'одностороннее копирование со стекла'
    UNION ALL SELECT 'abadd', 'двустороннее копирование со стекла'
    UNION ALL SELECT 'abae', 'матовая бумага 250 гр.'
    UNION ALL SELECT 'abaeb', 'двусторонняя печать'
    UNION ALL SELECT 'abaeс', 'одностороннее копирование со стекла'
    UNION ALL SELECT 'abaed', 'двустороннее копирование со стекла'
    UNION ALL SELECT 'abaf', 'матовая бумага 300 гр.'
    UNION ALL SELECT 'abafb', 'двусторонняя печать'
    UNION ALL SELECT 'abafс', 'одностороннее копирование со стекла'
    UNION ALL SELECT 'abafd', 'двустороннее копирование со стекла'
    UNION ALL SELECT 'abag', 'глянцевая бумага 170 гр.'
    UNION ALL SELECT 'abagb', 'двусторонняя печать'
    UNION ALL SELECT 'abagс', 'одностороннее копирование со стекла'
    UNION ALL SELECT 'abagd', 'двустороннее копирование со стекла'
    UNION ALL SELECT 'abah', 'глянцевая бумага 250 гр.'
    UNION ALL SELECT 'abahb', 'двусторонняя печать'
    UNION ALL SELECT 'abahс', 'одностороннее копирование со стекла'
    UNION ALL SELECT 'abahd', 'двустороннее копирование со стекла'
    UNION ALL SELECT 'abai', 'самоклейка'
    UNION ALL SELECT 'abb', 'формат А3'
    UNION ALL SELECT 'abba', 'обычная бумага 80 гр.'
    UNION ALL SELECT 'abbab', 'двусторонняя печать'
    UNION ALL SELECT 'abbaс', 'одностороннее копирование со стекла'
    UNION ALL SELECT 'abbad', 'двустороннее копирование со стекла'
    UNION ALL SELECT 'abbb', 'матовая бумага 160 гр.'
    UNION ALL SELECT 'abbbb', 'двусторонняя печать'
    UNION ALL SELECT 'abbbс', 'одностороннее копирование со стекла'
    UNION ALL SELECT 'abbbd', 'двустороннее копирование со стекла'
    UNION ALL SELECT 'abbc', 'матовая бумага 200 гр.'
    UNION ALL SELECT 'abbcb', 'двусторонняя печать'
    UNION ALL SELECT 'abbcс', 'одностороннее копирование со стекла'
    UNION ALL SELECT 'abbcd', 'двустороннее копирование со стекла'
    UNION ALL SELECT 'abbd', 'матовая бумага 250 гр.'
    UNION ALL SELECT 'abbdb', 'двусторонняя печать'
    UNION ALL SELECT 'abbdс', 'одностороннее копирование со стекла'
    UNION ALL SELECT 'abbdd', 'двустороннее копирование со стекла'
    UNION ALL SELECT 'abbe', 'матовая бумага 280 гр.'
    UNION ALL SELECT 'abbeb', 'двусторонняя печать'
    UNION ALL SELECT 'abbeс', 'одностороннее копирование со стекла'
    UNION ALL SELECT 'abbed', 'двустороннее копирование со стекла'
    UNION ALL SELECT 'abbf', 'глянцевая бумага 170 гр.'
    UNION ALL SELECT 'abbfb', 'двусторонняя печать'
    UNION ALL SELECT 'abbfc', 'одностороннее копирование со стекла'
    UNION ALL SELECT 'abbfd', 'двустороннее копирование со стекла'
    UNION ALL SELECT 'abc', 'формат А2'
    UNION ALL SELECT 'abca', 'обычная бумага 80 гр.'
    UNION ALL SELECT 'abcb', 'калька 90 гр.'
    UNION ALL SELECT 'abd', 'формат А1'
    UNION ALL SELECT 'abda', 'обычная бумага 80 гр.'
    UNION ALL SELECT 'abdb', 'калька 90 гр.'
    UNION ALL SELECT 'abe', 'формат А0'
    UNION ALL SELECT 'abea', 'обычная бумага 80 гр.'
    UNION ALL SELECT 'abeb', 'калька 90 гр.'
    UNION ALL SELECT 'abf', 'нестандартный формат'
    UNION ALL SELECT 'abfa', 'обычная бумага 80 гр.'
    UNION ALL SELECT 'abfb', 'калька 90 гр.'
    UNION ALL SELECT 'ba', 'Переплет пластиковой пружиной'
    UNION ALL SELECT 'baa', 'формат А4'
    UNION ALL SELECT 'baaa', 'маленькая пружина'
    UNION ALL SELECT 'baaab', '(переброшюровка)'
    UNION ALL SELECT 'baab', 'средняя пружина'
    UNION ALL SELECT 'baabb', '(переброшюровка)'
    UNION ALL SELECT 'baac', 'большая пружина'
    UNION ALL SELECT 'baacb', '(переброшюровка)'
    UNION ALL SELECT 'bab', 'формат А3'
    UNION ALL SELECT 'baba', 'маленькая пружина'
    UNION ALL SELECT 'babab', '(переброшюровка)'
    UNION ALL SELECT 'babb', 'средняя пружина'
    UNION ALL SELECT 'babbb', '(переброшюровка)'
    UNION ALL SELECT 'babc', 'большая пружина'
    UNION ALL SELECT 'babcb', '(переброшюровка)'
    UNION ALL SELECT 'bb', 'Переплет металлической пружиной'
    UNION ALL SELECT 'bc', 'Твердый переплет'
    UNION ALL SELECT 'bca', 'корешок 5-7 мм.'
    UNION ALL SELECT 'bcab', '(переброшюровка)'
    UNION ALL SELECT 'bcb', 'корешок 10-13 мм.'
    UNION ALL SELECT 'bcbb', '(переброшюровка)'
    UNION ALL SELECT 'bcc', 'корешок 16-20 мм.'
    UNION ALL SELECT 'bccb', '(переброшюровка)'
    UNION ALL SELECT 'bcd', 'корешок 24-32 мм.'
    UNION ALL SELECT 'bcdb', '(переброшюровка)'
    UNION ALL SELECT 'bd', 'Вставка конверта для CD'
    UNION ALL SELECT 'be', 'Вставка файла в переплёт'
    UNION ALL SELECT 'cba', 'Глянцевое ламинирование'
    UNION ALL SELECT 'cbaa', 'формат А6'
    UNION ALL SELECT 'cbab', 'формат А5'
    UNION ALL SELECT 'cbac', 'формат А4'
    UNION ALL SELECT 'cbad', 'формат А3'
    UNION ALL SELECT 'cbb', 'Матовое ламинирование'
    UNION ALL SELECT 'cbba', 'формат А6'
    UNION ALL SELECT 'cbbb', 'формат А5'
    UNION ALL SELECT 'cbbc', 'формат А4'
    UNION ALL SELECT 'cbbd', 'формат А3'
    UNION ALL SELECT 'co', 'Фальцовка'
    UNION ALL SELECT 'cl', 'Резка'
    UNION ALL SELECT 'cm', 'Ручная резка'
    UNION ALL SELECT 'cr', 'Отправка/прием файлов через интернет'
    UNION ALL SELECT 'ce', 'Работа на компьютере'
    UNION ALL SELECT 'cf', 'Набор текста сотрудником компании'
    UNION ALL SELECT 'cg', 'Доработка файлов клиента сотрудником компании'
    UNION ALL SELECT 'ch', 'Распознавание текста'
    UNION ALL SELECT 'ci', 'Запись на CD/DVD'
    UNION ALL SELECT 'cia', 'диск клиента'
    UNION ALL SELECT 'cib', 'диск компании'
    UNION ALL SELECT 'cj', 'Сшивание/расшивание'
    UNION ALL SELECT 'ck', 'Перфорация листов'
    UNION ALL SELECT 'cn', 'Степлер'
    UNION ALL SELECT 'cp', 'Биговка'
    UNION ALL SELECT 'cq', 'Тиснение'
    UNION ALL SELECT 'cs', 'Доставка'
    UNION ALL SELECT 'ct', 'Папка скоросшиватель'
    UNION ALL SELECT 'cu', 'Файл A4'
    UNION ALL SELECT 'cv', 'Файл A3'
    UNION ALL SELECT 'da', 'Услуги дизайнера'
    UNION ALL SELECT 'db', 'Верстка визитки'
    UNION ALL SELECT 'dca', 'Печать односторонней черно белой визитки'
    UNION ALL SELECT 'dcb', 'Печать двусторонней черно белой визитки'
    UNION ALL SELECT 'dcc', 'Печать односторонней цветной визитки'
    UNION ALL SELECT 'dcd', 'Печать двусторонней цветной визитки'
    UNION ALL SELECT 'dda', 'Дизайнерская бумага'
    UNION ALL SELECT 'ddb', 'Touche Cover'
    UNION ALL SELECT 'de', 'Фото на документы'
    UNION ALL SELECT 'dfa', 'Изготовление круглой печати, штампа или факсимиле'
    UNION ALL SELECT 'dfb', 'Изготовление маленького штампа'
    UNION ALL SELECT 'dfc', 'Изготовление печати или штампа по оттиску'
    UNION ALL SELECT 'dfd', 'Изготовление личной печати, экслибриса'
    UNION ALL SELECT 'dga', 'Автоматическая оснастка GBR'
    UNION ALL SELECT 'dgb', 'Простая оснастка'
    UNION ALL SELECT 'dgc', 'Карманная печать'
    UNION ALL SELECT 'dgd', 'Автоматическая оснастка для маленьких штампов'
    UNION ALL SELECT 'dge', 'Автоматическая оснастка для больших штампов'
    UNION ALL SELECT 'dha', 'Подушка 2 pads 50x90'
    UNION ALL SELECT 'dhb', 'Подушка 2 pads 70x110'
    UNION ALL SELECT 'dhc', 'Подушка 50x90'
    UNION ALL SELECT 'dhd', 'Подушка 70x110'
    UNION ALL SELECT 'dhe', 'Краска'
    UNION ALL SELECT 'di', 'Фоторетушь'
    UNION ALL SELECT 'dj', 'Верстка макета'
    UNION ALL SELECT 'dk', 'Разработка логотипа'
    UNION ALL SELECT 'ea', 'Накатка на пенокартон'
    UNION ALL SELECT 'eaa', '5 мм'
    UNION ALL SELECT 'eaaa', 'формат А4'
    UNION ALL SELECT 'eaab', 'формат А3'
    UNION ALL SELECT 'eaac', 'формат А2'
    UNION ALL SELECT 'eaad', 'формат А1'
    UNION ALL SELECT 'eaae', 'формат А1'
    UNION ALL SELECT 'eaaf', '1 кв.м'
    UNION ALL SELECT 'eab', '10 мм'
    UNION ALL SELECT 'eaba', 'формат А4'
    UNION ALL SELECT 'eabb', 'формат А3'
    UNION ALL SELECT 'eabc', 'формат А2'
    UNION ALL SELECT 'eabd', 'формат А1'
    UNION ALL SELECT 'eabe', 'формат А0'
    UNION ALL SELECT 'eabf', '1 кв.м'
    UNION ALL SELECT 'eb', 'Накатка на п/к для студентов'
    UNION ALL SELECT 'eba', '5 мм'
    UNION ALL SELECT 'ebaa', 'формат А4'
    UNION ALL SELECT 'ebab', 'формат А3'
    UNION ALL SELECT 'ebac', 'формат А2'
    UNION ALL SELECT 'ebad', 'формат А1'
    UNION ALL SELECT 'ebae', 'формат А1'
    UNION ALL SELECT 'ebaf', '1 кв.м'
    UNION ALL SELECT 'ebb', '10 мм'
    UNION ALL SELECT 'ebba', 'формат А4'
    UNION ALL SELECT 'ebbb', 'формат А3'
    UNION ALL SELECT 'ebbc', 'формат А2'
    UNION ALL SELECT 'ebbd', 'формат А1'
    UNION ALL SELECT 'ebbe', 'формат А0'
    UNION ALL SELECT 'ebbf', '1 кв.м'
    UNION ALL SELECT 'ga', 'Фальцовка'
    UNION ALL SELECT 'gaa', 'А4'
    UNION ALL SELECT 'gab', 'А3'
    UNION ALL SELECT 'gac', 'А2'
    UNION ALL SELECT 'gad', 'А1'
    UNION ALL SELECT 'gae', 'А0'
    UNION ALL SELECT 'gb', 'Сканирование (цветное)'
    UNION ALL SELECT 'gba', 'А2'
    UNION ALL SELECT 'gbb', 'А1'
    UNION ALL SELECT 'gbc', 'А0'
    UNION ALL SELECT 'gсa', 'Сканирование формат А4'
    UNION ALL SELECT 'gсab', 'со стекла'
    UNION ALL SELECT 'gсb', 'Сканирование формат А3'
    UNION ALL SELECT 'gсbb', 'со стекла'
    UNION ALL SELECT 'gсc', 'Сканирование формат А2'
    UNION ALL SELECT 'gсd', 'Сканирование формат А1'
    UNION ALL SELECT 'gсe', 'Сканирование формат А0'
) AS new_rows
WHERE NOT EXISTS (SELECT 1 FROM `titel_calc_ur` t WHERE t.`name` = new_rows.`name`);
